- app/api/routers/login.py
- app/db/db.py
- app/main.py
> <Refactor> : 디렉토리 리팩토링

- app/api/routers/login.py
- app/api/routers/task.py
- app/crud/task.py
- app/crud/user.py
- app/main.py
front 페이지와 api 통신
1. 문제 페이지로 보낼 view 생성
2. 문제 클릭 시 해당 id로 db 검색한 결과 return
> Feature {upload task}

- app/api/routers/task.py
- app/crud/board.py
- app/crud/task.py
- app/crud/user.py
1. 문제 페이지 api 수정
1. sql 쿼리문 수정
2. 문제 페이지 리턴 값 수정
> <Feat> :  문제 페이지

- app/api/routers/scoring.py
- app/api/routers/status.py
- app/core/celery_worker.py
- app/crud/status.py
- app/crud/submission.py
- app/crud/user.py
- app/main.py
- app/schemas/submission.py
> Feature {채점상황}

- app/api/routers/board.py
- app/api/routers/login.py
- app/crud/board.py
1. board api 기능 구현
1. 문제 상세 페이지 api 구현
2. 빠른 글쓰기 api 구현
> <Feat> :  Board

- app/api/routers/board.py
- app/crud/board.py
- app/crud/user.py
게시판 api 수정
1. 게시글 작성자 리턴 추가
2. 게시판 시간순으로 정렬
3. 게시판 조회수 및 좋아요 api 구현
4. 댓글 작성 및 좋아요 api 구현
1. 내가 작성한 게시글 삭제
2. 내가 작성한 댓글 삭제
> Feature {comments}

- app/api/routers/board.py
- app/crud/board.py
- 게시판 삭제
1. 게시글 삭제 api 구현
2. 댓글 삭제 api 구현
> <Feat> :  게시판

- app/api/routers/scoring.py
- app/core/celery_worker.py
- app/crud/submission.py
- app/crud/user.py
> Feature {제출결과확인}

- app/api/routers/task.py
- app/crud/task.py
> Feature {문제업로드}

- app/api/routers/hot.py
- app/crud/hot.py
- app/db/__init__.py
- app/main.py
> Feature {hot}

- .gitignore
- app/api/routers/admin.py
- app/api/routers/authentication.py
- app/api/routers/login.py
- app/core/admin.py
- app/core/security.py
- app/crud/user.py
- app/main.py
- app/schemas/login.py
> Feature {인증}

- app/api/routers/board.py
- app/api/routers/hot.py
- app/api/routers/mypage.py
- app/core/security.py
- app/crud/base.py
- app/crud/hot.py
- app/crud/mypage.py
- app/db/__init__.py
- app/main.py
- app/schemas/mypage.py
마이페이지 api
1. 비밀번호 수정 api
2. 이메일 수정 api
3. 마이페이지 내에서 내가 쓴 게시글 삭제
4. 내가 쓴 게시글 리스트
5. Auto Increment 수정
6. 마이페이지 내 정보 첫번째 박스
> Feature {manage}

- .gitignore
- app/api/routers/scoring.py
- app/core/celery_worker.py
- app/crud/submission.py
- app/crud/task.py
- app/crud/user.py
- app/schemas/submission.py
C언어 채점, 문제 정답률, 유저 경험치
1. C언어 코드 채점 추가
2. 문제별 정답률 추가
3. 유저 경험치 추가
> Feature {c언어채점}

- app/api/routers/mypage.py
- app/crud/mypage.py
1. 내가 푼 문제
1. 푼 문제 수 및 정답률
3. 맞은 문제 리스트 전송
4. 틀린 문제 리스트 전송
5. 월별 푼 문제 수 전송
6. 내 성장 그래프 전송
> <Feat> :  내가 푼 문제들

- .gitignore
- app/api/routers/image.py
- app/core/celery_worker.py
- app/core/image.py
- app/db/__init__.py
- app/main.py
type별 이미지 업로드 및 다운로드
1. type별 이미지 업로드 및 다운로드
2. 이미지 업로드 경로 생성
3. 파일 경로 .env 파일로 이동 -> 그에따른 참조 변경
4. gitignore 변경
> <Feat> : 이미지 업/다운로드

- app/api/routers/login.py
- app/core/security.py
자동로그인 api 추가
1. 자동로그인 체크시 토큰 유효기간 일주일 아닐 시 3시간
> <Feat> : 자동로그인 api 추가

- app/api/routers/status.py
- app/api/routers/task.py
- app/crud/status.py
- app/crud/task.py
문제 검색 및 채점 상황
1. 문제 페이지 문제 검색 api
2. 채점 상황 옵션별 정렬 api
3. 채점 상황 문제별 api
> <Feat> :  문제 검색 및 채점 상황

- app/api/routers/hot.py
- app/api/routers/mypage.py
- app/crud/hot.py
- app/crud/mypage.py
> <Feat> :  홈화면 그래프

- app/api/routers/mypage.py
- app/crud/mypage.py
- app/schemas/mypage.py
내 문제집 api
1. 내 문제집 추가 post api
2. 마이페이지 내 문제집 get api
3. 내 문제집 삭제 post api
> Feature {my tasks}

- app/api/routers/std_manage.py
- app/crud/mypage.py
- app/crud/std_manage.py
- app/main.py
- app/schemas/std_manage.py
학생관리 api
1. 학생 리스트 get api
2. 관리할 학생 등록 post api
3. 관리중인 학생 리스트 get api
4. 등록한 학생 제거 post api
> <Feat> :  학생관리

- app/api/routers/mypage.py
- app/crud/mypage.py
내 문제집 api
1. 내 문제집 풀었는지 여부 추가
2. 내 문제집에서 삭제 post api
> <Feat> :  내 문제집

- app/api/routers/group.py
- app/crud/group.py
- app/main.py
그룹 보기
1. 전체 그룹 리스트 get api
2.  내 그룹 get api
> <Feat> :  그룹

- app/api/routers/group.py
- app/crud/base.py
- app/crud/group.py
- app/crud/user.py
- app/schemas/group.py
그룹 삭제
1. 그룹 나가기 api
2. 그룹 삭제 api
3. 그룹 삭제 후 그룹 테이블 AI 재정렬 및 초기화
> Feature {group}

- app/api/routers/admin.py
- app/api/routers/image.py
- app/api/routers/task.py
- app/core/admin.py
- app/core/image.py
- app/crud/task.py
- app/schemas/admin.py
- app/schemas/task.py
- notice/notice.txt
> Feature {image}

- app/api/routers/group.py
- app/crud/group.py
그룹 삭제
1. 그룹 삭제 api
2. 그룹 삭제 시 해당 그룹의 게시글 삭제
3. 게시글의 댓글 삭제
> <Feat> :  그룹 삭제

- app/api/routers/admin.py
- app/api/routers/mypage.py
- app/crud/mypage.py
- app/crud/user.py
- app/main.py
- app/schemas/mypage.py
내 게시글 삭제 api
내가 작성한 게시글 마이페이지에서 삭제
> Feature {managers}

- app/api/routers/group.py
- app/crud/group.py
1. 그룹문제집에 문제 추가
1. 그룹문제집에 문제 추가 api
> <fix> : 그룹 문제집 #94

- app/api/routers/room.py
- app/crud/room.py
- app/crud/user.py
- app/schemas/room.py
> <Feat> : 학습 로드맵 생성 및 수정

- app/api/routers/board.py
- app/crud/base.py
- app/crud/board.py
- app/schemas/board.py
board 기능 리팩토링
1. response model 추가
2. crud에 맞는 api method로 변경
3. 주석 작성
4. 필요없는 param 제거
5. mysql의 기능 적극 활용
6.
> <Refactor> : board 기능 리팩토링

- app/api/routers/admin.py
- app/api/routers/task.py
- app/core/celery_worker.py
- app/core/image.py
- app/crud/task.py
- app/schemas/task.py
task 리팩토링 및 문제 수정 기능 추가
1. task 리팩토링
2. 문제 수정 기능 추가
3. 문제 관련 페이지네이션 추가
#63
> Refactor {task}

- Dockerfile
- app/__init__.py
- app/api/routers/room.py
- app/crud/room.py
- requirements.txt
로드맵 정보 리턴
1. 로드맵의 정보 리턴
2. 로드맵 내 문제 리스트 리턴
3. 스터디룸 멤버가 푼 문제 리스트 리턴
> Feature {docker} co 25

- app/api/routers/room.py
- app/crud/room.py
- app/schemas/room.py
질문 답변 채택 
1. 질문 답변 채택 여부 API
3. 답변 채택 API
4. 채택된 답변이 있는 질문인지
5.
> <Feat> :  답변 채택

- app/crud/room.py
- app/schemas/room.py
> <Feat> :  질문 작성 시간

- app/crud/room.py
- app/schemas/room.py
질문 작성자
1. 질문 작성자 id, 레벨 및 작성 시간 리턴
> <Feat> :  질문 작성자

- app/api/routers/login.py
- app/api/routers/room.py
- app/crud/alarm.py
- app/crud/board.py
- app/crud/room.py
- app/crud/user.py
- app/schemas/room.py
- app/schemas/user.py
> <Feat> : 알람 백엔드

- app/api/routers/submission.py
- app/schemas/submission.py
제출 결과
1.  제출 결과, pylint API 통합
> <Feat> :  제출 결과

- app/api/routers/auth.py
- app/api/routers/user.py
- app/crud/alarm.py
- app/schemas/user.py
알람 처리
1. 로그인 시 안읽은 알람 수 리턴
2. 알람 읽음 처리
> Feature {alarm} co 140

- app/api/routers/user.py
- app/crud/user.py
- app/schemas/user.py
레벨 api
1. exp 기준 유저 레벨 리턴
2. exp 기준 유저 순위 리턴
> <Feat> :  레벨
